config/routes.rb
Shipdaily::Application.routes.draw do
  get "static/index"

  get "static/about"

  root :to => "static#index"
  match "/auth/:provider" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth.fetch("provider")
      user.uid = auth.fetch('uid')
      user.name = auth["info"].fetch("name")
      user.email = auth["info"].fetch("email")
      user.github_url = auth["info"]["urls"].fetch("GitHub")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  helper_method :current_user
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to "/auth/#{params[:provider]}"
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in."
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out."
  end

  def failure
    redirect_to root_url, :alert => "Authentication failed, please try again."
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    puts current_user.inspect
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:"http-equiv"=>"Content-Type", :content => "text/html; charset=utf-8" }
    %title= "ShipDaily &mdash; an ang.st blood pact"
    %meta{:name=>"Robots", :content=>"index,all"}
    = csrf_meta_tag
    = javascript_include_tag :defaults
    = stylesheet_link_tag "style"
    
  %body
    %div#wrapper
      #header 
        %h1
          = link_to "ShipDaily", root_url
        #auth
        - if current_user
          Signed in as
          =link_to current_user.name, current_user.github_url
          =link_to "Logout", logout_url
        - else
          =link_to "Login", login_url("github")
      #content
        = yield
      
      #footer
        %p an ang.st blood pact.